<?php
if(!defined('ABSPATH')) {
    exit;
}

// Add the menu item to the admin menu for settings
add_action('admin_menu', 'ai_tts_add_admin_menu');
function ai_tts_add_admin_menu() {
    add_options_page(esc_html__('AI Text-to-Speech', 'ai-text-to-speech'), esc_html__('AI Text-to-Speech', 'ai-text-to-speech'), 'manage_options', 'ai-text-to-speech', 'ai_tts_options_page');
}

// Get Specific Option
function ai_tts_get_option($option) {
    $options = get_option('ai_tts_settings');
    if(isset($options[$option]) && $options[$option] != '') {
        return sanitize_text_field($options[$option]);
    }
    $default_options = [
        'file_storage_location' => 'local',
        'dropbox_app_key' => '',
        'dropbox_app_secret' => '',
        'dropbox_access_token' => '',
        'show_player_label' => true,
        'player_label' => 'Listen to the audio version of this article (generated by AI).',
        'player_background_color' => '#f1f1f1',
        'player_speed' => '1',
        'post_types' => 'all',
        'post_types_to_enable' => array(),
        'include_author' => true,
        'include_date' => true,
    ];
    $default_options = array_map('sanitize_text_field', $default_options);
    return $default_options[$option];
}

// Options page callback
function ai_tts_options_page() {
    ?>
    <div class="wrap">
        <h1><?php echo esc_html__('AI Text-to-Speech', 'ai-text-to-speech'); ?></h1>
        <p><?php echo esc_html__('Settings for the AI Text-to-Speech plugin. When configured, you will be able to generate a TTS audio file for any post on your website, which is automatically displayed in an audio player at the top of the post content.', 'ai-text-to-speech'); ?></p>
        <hr/>
        <!-- Key input -->
        <form method="post" action="options.php">
            <?php settings_fields('ai_tts_settings'); ?>
            <?php do_settings_sections('ai_tts_settings'); ?>
            <table class="form-table">
                <!-- OpenAI API Key (Not saved in the single option) -->
                <tr valign="top">
                    <th scope="row"><?php echo esc_html__('OpenAI API Secret Key', 'ai-text-to-speech'); ?></th>
                    <td>
                        <?php
                        $api_key = get_option('ai_tts_api_key');
                        $disabled = '';
                        $placeholder = '';
                        $title = '';
                        if(defined('AI_TTS_API_KEY')) {
                            $api_key = AI_TTS_API_KEY;
                            $api_key = substr($api_key, 0, strlen($api_key) / 2) . str_repeat('*', strlen($api_key) / 2);
                            $disabled = 'disabled';
                            $placeholder = 'placeholder="' . esc_html__('*Set in wp-config.php*', 'ai-text-to-speech') . '"';
                            $title = 'title="' . esc_html__('This option is set in wp-config.php', 'ai-text-to-speech') . '"';
                        }
                        ?>
                        <input type="text" name="ai_tts_api_key" value="<?php echo esc_attr($api_key); ?>" <?php echo $disabled; ?> <?php echo $placeholder; ?> <?php echo $title; ?> />
                        <!-- API Help Button -->
                        <p>
                            <a class="api-help-button" href="#"><?php echo esc_html__('How to get started', 'ai-text-to-speech'); ?><span class="dashicons dashicons-arrow-down-alt2" style="text-decoration: none; font-size: 14px; margin-top: 5px;"></span></a>
                        </p>
                        <p class="api-help" style="display: none; padding: 10px; background-color: #fff; border-radius: 5px;">
                            - <?php echo sprintf(wp_kses_post(__('To get started, you will need to <a href="%s" target="_blank">create an account with OpenAI</a>.', 'ai-text-to-speech')), 'https://platform.openai.com/signup'); ?>
                            <br/>- <?php echo esc_html__('Once you have created an account, you can generate an API secret key here:', 'ai-text-to-speech'); ?> <a href="https://platform.openai.com/api-keys" target="_blank"><?php echo esc_html__('Generate API Key', 'ai-text-to-speech'); ?></a> 
                            <br/>- <?php echo esc_html__('Copy and paste the API key into the field above, and click Save Changes.', 'ai-text-to-speech'); ?>
                            <br/>- <?php echo esc_html__('You can then generate TTS audio files for your posts, in the "AI Text to Speech" section of the post editor sidebar.', 'ai-text-to-speech'); ?>
                        </p>
                    </td>
                </tr>
                <!-- On Click API Help Button, show the API Help -->
                <script>
                jQuery(document).ready(function($) {
                    $('.api-help-button').click(function() {
                        if($('.api-help').is(':visible')) {
                            $('.api-help').css('display', 'none');
                        } else {
                            $('.api-help').css('display', 'inline-block');
                        }
                    });
                });
                </script>
                <!-- Pricing information -->
                <tr>
                    <th scope="row"><?php echo esc_html__('OpenAI TTS Pricing', 'ai-text-to-speech'); ?></th>
                    <td>
                        <p><?php echo esc_html__('OpenAI charges $0.015 per 1000 characters converted from text to spoken audio.', 'ai-text-to-speech'); ?> <a href="https://openai.com/pricing" target="_blank"><?php echo esc_html__('Read more about the pricing here.', 'ai-text-to-speech'); ?></a></p>
                        <p><?php echo esc_html__('Note: It is your responsibility to keep track of your usage and cost in your', 'ai-text-to-speech'); ?> <a href="https://platform.openai.com/" target="_blank"><?php echo esc_html__('OpenAI account', 'ai-text-to-speech'); ?></a>. <?php echo sprintf(wp_kses_post(__('Be sure to <a href="%s">set your own monthly usage limits</a>.', 'ai-text-to-speech')), 'https://platform.openai.com/account/limits'); ?></p>
                    </td>
                </tr>
                <!-- Show current OpenAI monthly spend -->
                <tr valign="top">
                    <th scope="row"><?php echo esc_html__('OpenAI Usage Today', 'ai-text-to-speech'); ?></th>
                    <td>
                        <?php
                        $api_key = get_option('ai_tts_api_key');

                        if ($api_key) {
                            $date = gmdate('Y-m-d');
                            $url = 'https://api.openai.com/v1/usage?date=' . $date;
                            $args = array(
                                'headers' => array(
                                    'Authorization' => 'Bearer ' . $api_key
                                )
                            );

                            $response = wp_remote_get($url, $args);

                            // Check for WP_Error or non-200 status code.
                            if (is_wp_error($response) || 200 !== wp_remote_retrieve_response_code($response)) {
                                echo esc_html__('Error fetching data.', 'ai-text-to-speech');
                                return;
                            }

                            $body = json_decode(wp_remote_retrieve_body($response));

                            // Process the response body.
                            $total_characters_used = 0;
                            $total_requests = 0;

                            if (isset($body->tts_api_data) && is_array($body->tts_api_data)) {
                                foreach ($body->tts_api_data as $item) {
                                    // Ensure that the required properties exist.
                                    if (isset($item->num_characters) && isset($item->num_requests)) {
                                        $total_characters_used += $item->num_characters;
                                        $total_requests += $item->num_requests;
                                    }
                                }
                            }

                            // Output the results.
                            echo esc_html__('Total Characters Used:', 'ai-text-to-speech') . " " . esc_html($total_characters_used) . "<br>";
                            echo esc_html__('Total Requests:', 'ai-text-to-speech') . " " . esc_html($total_requests);
                            $total_cost = $total_characters_used / 1000 * 0.015;
                            $total_cost = round($total_cost, 2);
                            echo "<br>" . esc_html__('Total Cost:', 'ai-text-to-speech') . " $" . esc_html($total_cost);
                        } else {
                            echo esc_html__('No API key set.', 'ai-text-to-speech');
                        }
                        ?>
                    </td>
                </tr>
                </table>

                <hr/>

                <table class="form-table">
                <!-- Select file storage location -->
                <tr valign="top">
                    <th scope="row"><?php echo esc_html__('File Storage Location', 'ai-text-to-speech'); ?></th>
                    <td>
                        <select name="ai_tts_settings[file_storage_location]">
                            <option value="local" <?php selected(ai_tts_get_option('file_storage_location'), 'local'); ?>><?php echo esc_html__('Local', 'ai-text-to-speech'); ?></option>
                            <option value="dropbox" disabled><?php echo esc_html__('Third-Party Locations Coming Soon..', 'ai-text-to-speech'); ?></option>
                        </select>
                    </td>
                </tr>
                <!-- If Dropbox is selected, show the Dropbox API credentials -->
                <tr valign="top" class="ai-tts-dropbox-credentials" <?php if (ai_tts_get_option('file_storage_location') != 'dropbox') {
                    echo 'style="display: none;"';
                } ?>>
                    <th scope="row"><?php echo esc_html__('Dropbox App Key', 'ai-text-to-speech'); ?></th>
                    <td><input type="text" name="ai_tts_settings[dropbox_app_key]" value="<?php echo esc_attr(ai_tts_get_option('dropbox_app_key')); ?>" /></td>
                </tr>
                <tr valign="top" class="ai-tts-dropbox-credentials" <?php if (ai_tts_get_option('file_storage_location') != 'dropbox') {
                    echo 'style="display: none;"';
                } ?>>
                    <th scope="row"><?php echo esc_html__('Dropbox App Secret', 'ai-text-to-speech'); ?></th>
                    <td><input type="text" name="ai_tts_settings[dropbox_app_secret]" value="<?php echo esc_attr(ai_tts_get_option('dropbox_app_secret')); ?>" /></td>
                </tr>
                <tr valign="top" class="ai-tts-dropbox-credentials" <?php if (ai_tts_get_option('file_storage_location') != 'dropbox') {
                    echo 'style="display: none;"';
                } ?>>
                    <th scope="row"><?php echo esc_html__('Dropbox Access Token', 'ai-text-to-speech'); ?></th>
                    <td><input type="text" name="ai_tts_settings[dropbox_access_token]" value="<?php echo esc_attr(ai_tts_get_option('dropbox_access_token')); ?>" /></td>
                </tr>
                <!-- If Local is selected, show the Local credentials -->
                <tr valign="top" class="ai-tts-local-credentials" <?php if (ai_tts_get_option('file_storage_location') != 'local') {
                    echo 'style="display: none;"';
                } ?>>
                    <th scope="row"><?php echo esc_html__('Local Storage', 'ai-text-to-speech'); ?></th>
                    <td>
                        <p><?php echo esc_html__('Files are stored in the uploads directory at', 'ai-text-to-speech'); ?> <code>/wp-content/uploads/ai-text-to-speech/</code></p>
                    </td>
                </tr>
                <script>
                jQuery(document).ready(function($) {
                    // Show Dropbox credentials if Dropbox is selected
                    $('select[name="ai_tts_settings[file_storage_location]"]').change(function() {
                        if ($(this).val() == 'dropbox') {
                            $('.ai-tts-dropbox-credentials').show();
                        } elseif ($(this).val() == 'local') {
                            $('.ai-tts-local-credentials').show();
                        } else {
                            $('.ai-tts-dropbox-credentials').hide();
                        }
                    });
                    $('select[name="ai_tts_settings[file_storage_location]"]').trigger('change');
                });
                </script>
                </table>

                <hr/>

                <!-- Customisations -->
                <table class="form-table">
                    <!-- Show player label -->
                    <tr valign="top">
                        <th scope="row"><?php echo esc_html__('Show Player Label', 'ai-text-to-speech'); ?></th>
                        <td>
                            <input type="hidden" name="ai_tts_settings[show_player_label]" value="0">
                            <input type="checkbox" name="ai_tts_settings[show_player_label]" value="1" <?php checked(ai_tts_get_option('show_player_label'), true); ?> /> <?php echo esc_html__('Show a text label under the audio player.', 'ai-text-to-speech'); ?>
                            <p class="description" style="font-size: 12px;"><?php echo sprintf(wp_kses_post(__('Note: The <a href="%s" target="_blank">OpenAI usage policies</a> require you to provide a clear disclosure to end users that the TTS voice they are hearing is AI-generated and not a human voice.', 'ai-text-to-speech')), 'https://openai.com/policies/usage-policies'); ?></p>
                        </td>
                    </tr>
                    <script>
                    jQuery(document).ready(function($) {
                        // Show player label if show_player_label is checked
                        $('input[name="ai_tts_settings[show_player_label]"]').change(function() {
                            if ($(this).is(':checked')) {
                                $('.ai-tts-player-label').show();
                            } else {
                                $('.ai-tts-player-label').hide();
                            }
                        });
                        $('input[name="ai_tts_settings[show_player_label]"]').trigger('change');
                    });
                    </script>
                    <!-- Player label -->
                    <tr valign="top" class="ai-tts-player-label" <?php if (ai_tts_get_option('show_player_label') != true) { ?>style="display: none;"<?php } ?>>
                        <th scope="row"><?php echo esc_html__('Player Label', 'ai-text-to-speech'); ?></th>
                        <td>
                            <textarea name="ai_tts_settings[player_label]"
                            placeholder="<?php echo esc_html__('Listen to the audio version of this article (generated by AI).', 'ai-text-to-speech'); ?>
                            "><?php echo esc_attr(ai_tts_get_option('player_label')); ?></textarea>
                        </td>
                    </tr>
                </table>

                <hr/>

                <!-- Post Types -->
                <table class="form-table">
                    <!-- Select Field either "All" or "Specific" -->
                    <tr valign="top">
                        <th scope="row"><?php echo esc_html__('Post Types', 'ai-text-to-speech'); ?></th>
                        <td>
                            <select name="ai_tts_settings[post_types]">
                                <option value="all" <?php selected(ai_tts_get_option('post_types'), 'all'); ?>><?php echo esc_html__('All', 'ai-text-to-speech'); ?></option>
                                <option value="specific" <?php selected(ai_tts_get_option('post_types'), 'specific'); ?>><?php echo esc_html__('Specific', 'ai-text-to-speech'); ?></option>
                            </select>
                            <p>
                                <?php echo esc_html__('Select which post types you would like to enable the TTS feature for.', 'ai-text-to-speech'); ?>
                        </td>
                    </tr>
                    <!-- Post Types To Enable -->
                    <tr valign="top" class="ai-tts-post-types">
                        <th scope="row"><?php echo esc_html__('Post Types To Enable', 'ai-text-to-speech'); ?></th>
                        <td>
                            <?php
                            global $post;
                            $the_types = ai_tts_get_option('post_types_to_enable');
                            if(!is_array($the_types)) {
                                $the_types = array();
                            }
                            $post_types = get_post_types(array('public' => true));
                            foreach ($post_types as $post_type) {
                                if(!$post_type) {
                                    continue;
                                }
                                ?>
                                <input type="checkbox" name="ai_tts_settings[post_types_to_enable][]"
                                value="<?php echo esc_attr($post_type); ?>" <?php if (in_array($post_type, $the_types)) {
                                    echo 'checked';
                                } ?> /> <?php echo esc_html($post_type); ?><br>
                                <?php
                            }
                            ?>
                        </td>
                    </tr>
                    <script>
                    jQuery(document).ready(function($) {
                        // Show post types if specific is selected
                        $('select[name="ai_tts_settings[post_types]"]').change(function() {
                            if ($(this).val() == 'specific') {
                                $('.ai-tts-post-types').show();
                            } else {
                                $('.ai-tts-post-types').hide();
                            }
                        });
                        $('select[name="ai_tts_settings[post_types]"]').trigger('change');
                    });
                    </script>
                </table>

                <hr/>

                <table class="form-table">
                    <!-- Include "Author" in the TTS -->
                    <tr valign="top">
                        <th scope="row">
                            <?php echo esc_html__('Author Name', 'ai-text-to-speech'); ?>
                        </th>
                        <td>
                            <input type="hidden" name="ai_tts_settings[include_author]" value="0" />
                            <input type="checkbox" name="ai_tts_settings[include_author]" value="1" <?php checked(ai_tts_get_option('include_author'), true); ?> />
                            <?php echo esc_html__('Include the "By *author name*" after the title, in the TTS for type "posts".', 'ai-text-to-speech'); ?>
                        </td>
                    </tr>
                    <!-- Include "Post Date" in the TTS -->
                    <tr valign="top">
                        <th scope="row">
                            <?php echo esc_html__('Post Date', 'ai-text-to-speech'); ?>
                        </th>
                        <td>
                            <input type="hidden" name="ai_tts_settings[include_date]" value="0" />
                            <input type="checkbox" name="ai_tts_settings[include_date]" value="1" <?php checked(ai_tts_get_option('include_date'), true); ?> />
                            <?php echo esc_html__('Include the "Published on *date*" after the title, in the TTS for type "posts".', 'ai-text-to-speech'); ?>
                        </td>
                    </tr>
                </table>

            <br/>

            <?php submit_button(); ?>

        </form>

        <br/><br/>
        
        <p style="font-size: 15px; font-weight: bold;"><?php echo esc_html__('Developed by', 'simple-cloudflare-turnstile'); ?> <a href="https://twitter.com/ElliotSowersby" target="_blank" title="@ElliotSowersby on Twitter"><span class="dashicons dashicons-twitter" style="margin-top: 5px; font-size: 15px; text-decoration: none;"></span>Elliot Sowersby</a> <a href="https://relywp.com/?utm_campaign=ai-tts-plugin&utm_source=plugin-settings&utm_medium=promo" target="_blank" title="RelyWP - WordPress Maintenance & Support"><span class="dashicons dashicons-admin-links" style="margin-top: 5px; font-size: 15px; text-decoration: none;"></span>RelyWP</a></p>

        <p style="font-size: 15px;">
            <a href="https://relywp.com/plugins/?utm_campaign=ai-tts-plugin&utm_source=plugin-settings&utm_medium=promo" target="_blank">
                <?php echo esc_html__( 'View more plugins by RelyWP', 'simple-cloudflare-turnstile' ); ?><span class="dashicons dashicons-external"
                style="font-size: 15px; margin-top: 5px; text-decoration: none;"></span>
            </a>
        </p>

    </div>
    <?php
}

add_action('admin_init', 'ai_tts_admin_init');
function ai_tts_admin_init() {
    register_setting('ai_tts_settings', 'ai_tts_api_key');
    register_setting('ai_tts_settings', 'ai_tts_settings');
}