<?php
if(!defined('ABSPATH')) {
    exit;
}

// Add the audio player to the top of the post content
add_filter('the_content', 'ai_tts_add_audio_player');
function ai_tts_add_audio_player($content) {
    if (is_single() && in_the_loop() && is_main_query()) {
        $tts_file_url = get_post_meta(get_the_ID(), 'ai_tts_file_url', true);
        if ($tts_file_url) {
            $audio_player = '<!-- AI Text-to-Speech Audio Player -->';
            $audio_player .= '<audio controls preload="metadata" src="' . esc_url($tts_file_url) . '"
            style="width: 100%; display: block; margin-bottom: 0px;"></audio>';
            $audio_player .= '<p style="font-size: 10px; text-align: center; margin-bottom: 25px; padding-bottom: 0;">Listen to the audio version of this article (generated by AI).</p>';
            $content = $audio_player . $content;
        }
    }
    return $content;
}